version: '3'

services:
  postgres:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-store:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-store:/data
    ports:
      - 6379:6379

volumes:
  postgres-store:
  redis-store:
